on:
  pull_request:
  push:
    branches:
      - master

name: Continuous integration

jobs:
  rustfmt:
    name: Rust Format
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - name: Add Rust tools to PATH
        run: echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
      - uses: dsherret/rust-toolchain-file@v1
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy Check
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - name: Add Rust tools to PATH
        run: echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
      - uses: dsherret/rust-toolchain-file@v1
      - run: cargo clippy --release --features=alloc,serde -- -D warnings

  dusk_analyzer:
    name: Dusk Analyzer
    uses: dusk-network/.github/.github/workflows/dusk-analysis.yml@main

  test_core:
    name: test core
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - name: Add Rust tools to PATH
        run: echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
      - uses: dsherret/rust-toolchain-file@v1
      - run: cargo test --release -p phoenix-core --features=alloc,serde

  test_core_no_default_serde:
    name: test core no-default-features serde
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - name: Add Rust tools to PATH
        run: echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
      - uses: dsherret/rust-toolchain-file@v1
      - run: cargo test --release -p phoenix-core --no-default-features --features=serde

  test_core_rkyv:
    name: test core rkyv compiles
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - name: Add Rust tools to PATH
        run: echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
      - uses: dsherret/rust-toolchain-file@v1
      - run: cargo test --release -p phoenix-core --features=rkyv-impl,alloc --no-run

  test_circuits:
    name: test cirucits
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - name: Add Rust tools to PATH
        run: echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
      - uses: dsherret/rust-toolchain-file@v1
      - run: cargo test --release -p phoenix-circuits

  test_circuits_no_default:
    name: test cirucits no-default-features
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - name: Add Rust tools to PATH
        run: echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
      - uses: dsherret/rust-toolchain-file@v1
      - run: cargo test --release -p phoenix-circuits --no-default-features --features=rkyv-impl,rkyv/size_16 --no-run

  compiles_to_wasm_with_serde:
    name: Compiles to wasm with serde enabled
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - name: Add Rust tools to PATH
        run: echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
      - uses: dsherret/rust-toolchain-file@v1
      - run: rustup target add wasm32-unknown-unknown
      - run: cargo b --release --no-default-features --features serde --target wasm32-unknown-unknown
        working-directory: core
