on:
  pull_request:
  push:
    branches:
      - master

name: Continuous integration

jobs:
  code-quality:
    name: Code quality
    uses: dusk-network/.github/.github/workflows/run-make.yml@main
    with:
      make_target: cq

  dusk_analyzer:
    name: Dusk Analyzer
    uses: dusk-network/.github/.github/workflows/dusk-analysis.yml@main

  test:
    name: Run tests
    uses: dusk-network/.github/.github/workflows/run-make.yml@main
    with:
      make_target: test

  test-no-std:
    name: No-std checks
    uses: dusk-network/.github/.github/workflows/run-make.yml@main
    with:
      make_target: test-no-std

  no-std:
    name: Bare-metal no_std
    uses: dusk-network/.github/.github/workflows/run-make.yml@main
    with:
      make_target: no-std
